/**
 * Injection tokens for configuration providers
 * These tokens are used to inject configuration objects into services
 */
export const CONFIG_TOKENS = {
  SERVER: 'SERVER_CONFIG',
  DATABASE: 'DATABASE_CONFIG',
  BATCH_WORKER: 'BATCH_WORKER_CONFIG',
  BUFFER: 'BUFFER_CONFIG',
  RETENTION: 'RETENTION_CONFIG',
  QUERY: 'QUERY_CONFIG',
  SERVICE: 'SERVICE_CONFIG',
  VALIDATION: 'VALIDATION_CONFIG',
  CHECKPOINT: 'CHECKPOINT_CONFIG',
  CIRCUIT_BREAKER: 'CIRCUIT_BREAKER_CONFIG',
  SHUTDOWN: 'SHUTDOWN_CONFIG',
  METRICS: 'METRICS_CONFIG',
  RATE_LIMITING: 'RATE_LIMITING_CONFIG',
} as const;

